<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GoogleHomePage</name>
   <tag></tag>
   <elementGuidId>24569653-aeea-4489-b902-a5eb36b7eb40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lst-ib</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
