<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Tweet</name>
   <tag></tag>
   <elementGuidId>26aabbbb-66fb-469a-a2e1-d183d1d27a24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html//a[@id='b']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
