<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_Logo</name>
   <tag></tag>
   <elementGuidId>68bc091a-caf4-47b9-aeb5-5b286ed07028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imagetrgt</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
