<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>object_allBooks</name>
   <tag></tag>
   <elementGuidId>06068521-70ac-4357-90e1-0c240417280a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#allBooks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;btnPurchase&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
