<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_droppable</name>
   <tag></tag>
   <elementGuidId>cbe75ce4-3ae5-4039-a61a-0ff7806f5eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#droppable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>droppable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
